## 💾 The data

You have access to the following files:

#### `data/group_fixtures.csv` — all 72 group stage matches
| Variable | Description |
|---|---|
| `match_id` | Unique match identifier |
| `group` | Group letter (A–L) |
| `home_team` | Home team name |
| `away_team` | Away team name |
| `date` | Match date (UTC) |
| `venue` | Stadium and city |

#### `data/knockout_slots.csv` — all 32 knockout round slots
| Variable | Description |
|---|---|
| `match_id` | Unique match identifier |
| `round` | Round name (e.g. `Quarter-final`) |
| `multiplier` | Score multiplier for this round |
| `slot_home` | Description of the home team slot (e.g. `Winner Group A`) |
| `slot_away` | Description of the away team slot |

| Variable | Description |
|---|---|

You may also bring in any external data—FIFA rankings, historical match results, player statistics—to build your predictions.

In [155]:
import pandas as pd

group_fixtures = pd.read_csv('data/group_fixtures.csv')
group_fixtures.head()

,match_id,group,home_team,away_team,date_utc,venue
0,1,A,Mexico,South Africa,2026-06-11T19:00:00Z,"Estadio Azteca, Mexico City"
1,2,A,South Korea,UEFA Playoff D,2026-06-12T02:00:00Z,"Estadio Akron, Guadalajara"
2,3,B,Canada,UEFA Playoff A,2026-06-12T19:00:00Z,"BMO Field, Toronto"
3,4,D,USA,Paraguay,2026-06-13T01:00:00Z,"SoFi Stadium, Los Angeles"
4,5,D,Australia,UEFA Playoff C,2026-06-13T04:00:00Z,"BC Place, Vancouver"

In [156]:
knockout_slots = pd.read_csv('data/knockout_slots.csv')
knockout_slots

,match_id,round,multiplier,date_utc,venue,slot_home,slot_away
0,73,Round of 32,1,2026-06-28T19:00:00Z,"SoFi Stadium, Los Angeles",Runner-up Group A,Runner-up Group B
1,74,Round of 32,1,2026-06-29T17:00:00Z,"NRG Stadium, Houston",Winner Group C,Runner-up Group F
2,75,Round of 32,1,2026-06-29T20:30:00Z,"Gillette Stadium, Boston",Winner Group E,Best 3rd (Groups A/B/C/D/F)
3,76,Round of 32,1,2026-06-30T01:00:00Z,"Estadio BBVA, Monterrey",Winner Group F,Runner-up Group C
4,77,Round of 32,1,2026-06-30T17:00:00Z,"AT&T Stadium, Dallas",Runner-up Group E,Runner-up Group I
5,78,Round of 32,1,2026-06-30T21:00:00Z,"MetLife Stadium, East Rutherford",Winner Group I,Best 3rd (Groups C/D/F/G/H)
6,79,Round of 32,1,2026-07-01T01:00:00Z,"Estadio Azteca, Mexico City",Winner Group A,Best 3rd (Groups C/E/F/H/I)
7,80,Round of 32,1,2026-07-01T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Group L,Best 3rd (Groups E/H/I/J/K)
8,81,Round of 32,1,2026-07-01T20:00:00Z,"Lumen Field, Seattle",Winner Group G,Best 3rd (Groups A/E/H/I/J)
9,82,Round of 32,1,2026-07-02T00:00:00Z,"Levi's Stadium, Santa Clara",Winner Group D,Best 3rd (Groups B/E/F/I/J)
10,83,Round of 32,1,2026-07-02T19:00:00Z,"BMO Field, Toronto",Runner-up Group K,Runner-up Group L
11,84,Round of 32,1,2026-07-02T23:00:00Z,"SoFi Stadium, Los Angeles",Winner Group H,Runner-up Group J
12,85,Round of 32,1,2026-07-03T03:00:00Z,"BC Place, Vancouver",Winner Group B,Best 3rd (Groups E/F/G/I/J)
13,86,Round of 32,1,2026-07-03T18:00:00Z,"AT&T Stadium, Dallas",Runner-up Group D,Runner-up Group G
14,87,Round of 32,1,2026-07-03T22:00:00Z,"Hard Rock Stadium, Miami",Winner Group J,Runner-up Group H
15,88,Round of 32,1,2026-07-04T01:30:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Group K,Best 3rd (Groups D/E/I/J/L)
16,89,Round of 16,2,2026-07-04T17:00:00Z,"NRG Stadium, Houston",Winner Match 73,Winner Match 75
17,90,Round of 16,2,2026-07-04T21:00:00Z,"Lincoln Financial Field, Philadelphia",Winner Match 74,Winner Match 77
18,91,Round of 16,2,2026-07-05T20:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 76,Winner Match 78
19,92,Round of 16,2,2026-07-06T00:00:00Z,"Estadio Azteca, Mexico City",Winner Match 79,Winner Match 80
20,93,Round of 16,2,2026-07-06T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 83,Winner Match 84
21,94,Round of 16,2,2026-07-07T00:00:00Z,"Lumen Field, Seattle",Winner Match 81,Winner Match 82
22,95,Round of 16,2,2026-07-07T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 86,Winner Match 88
23,96,Round of 16,2,2026-07-07T20:00:00Z,"BC Place, Vancouver",Winner Match 85,Winner Match 87
24,97,Quarter-final,4,2026-07-09T20:00:00Z,"Gillette Stadium, Boston",Winner Match 89,Winner Match 90
25,98,Quarter-final,4,2026-07-10T19:00:00Z,"SoFi Stadium, Los Angeles",Winner Match 93,Winner Match 94
26,99,Quarter-final,4,2026-07-11T21:00:00Z,"Hard Rock Stadium, Miami",Winner Match 91,Winner Match 92
27,100,Quarter-final,4,2026-07-12T01:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Match 95,Winner Match 96
28,101,Semi-final,8,2026-07-14T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 97,Winner Match 98
29,102,Semi-final,8,2026-07-15T19:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 99,Winner Match 100
30,103,Third-place playoff,8,2026-07-18T21:00:00Z,"Hard Rock Stadium, Miami",Loser Match 101,Loser Match 102
31,104,Final,16,2026-07-19T19:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 101,Winner Match 102

## 🗓️ Group stage predictions

Fill in your predictions for all 72 group stage matches below.

In [157]:
group_predictions = group_fixtures.copy()

# Fill in your predictions for each match
# Example (match 1 — Mexico vs South Africa): predicted_home_goals=2, predicted_away_goals=1, corners=9, yellow_cards=3, red_cards=0, winning_team='home'
group_predictions['predicted_home_goals'] = None   # e.g. 2
group_predictions['predicted_away_goals'] = None   # e.g. 1
group_predictions['corners']              = None   # e.g. 9
group_predictions['yellow_cards']         = None   # e.g. 3
group_predictions['red_cards']            = None   # e.g. 0
group_predictions['winning_team']         = None   # "home", "away", or "draw"

group_predictions

,match_id,group,home_team,away_team,date_utc,venue,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,winning_team
0,1,A,Mexico,South Africa,2026-06-11T19:00:00Z,"Estadio Azteca, Mexico City",None,None,None,None,None,None
1,2,A,South Korea,UEFA Playoff D,2026-06-12T02:00:00Z,"Estadio Akron, Guadalajara",None,None,None,None,None,None
2,3,B,Canada,UEFA Playoff A,2026-06-12T19:00:00Z,"BMO Field, Toronto",None,None,None,None,None,None
3,4,D,USA,Paraguay,2026-06-13T01:00:00Z,"SoFi Stadium, Los Angeles",None,None,None,None,None,None
4,5,D,Australia,UEFA Playoff C,2026-06-13T04:00:00Z,"BC Place, Vancouver",None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
67,68,L,Croatia,Ghana,2026-06-27T21:00:00Z,"Lincoln Financial Field, Philadelphia",None,None,None,None,None,None
68,69,K,Colombia,Portugal,2026-06-27T23:30:00Z,"Hard Rock Stadium, Miami",None,None,None,None,None,None
69,70,K,FIFA Playoff 1,Uzbekistan,2026-06-27T23:30:00Z,"Mercedes-Benz Stadium, Atlanta",None,None,None,None,None,None
70,71,J,Algeria,Austria,2026-06-28T02:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",None,None,None,None,None,None
71,72,J,Jordan,Argentina,2026-06-28T02:00:00Z,"AT&T Stadium, Dallas",None,None,None,None,None,None

## 🏆 Knockout stage predictions

For knockout matches you also predict **which teams are playing**. Fill in the team names based on your group stage predictions, then add your match predictions.

In [158]:
knockout_predictions = knockout_slots.copy()

# Fill in your predictions for each knockout match
# Example (match 73 — Round of 32): predicted_home_team='Brazil', predicted_away_team='France', predicted_home_goals=1, predicted_away_goals=0, corners=8, yellow_cards=2, red_cards=0, match_winner='home', penalties=False
knockout_predictions['predicted_home_team']  = None   # e.g. "Brazil"
knockout_predictions['predicted_away_team']  = None   # e.g. "France"
knockout_predictions['predicted_home_goals'] = None   # e.g. 1
knockout_predictions['predicted_away_goals'] = None   # e.g. 0
knockout_predictions['corners']              = None   # e.g. 8
knockout_predictions['yellow_cards']         = None   # e.g. 2
knockout_predictions['red_cards']            = None   # e.g. 0
knockout_predictions['match_winner']         = None   # "home" or "away"
knockout_predictions['penalties']            = None   # True or False

knockout_predictions

,match_id,round,multiplier,date_utc,venue,slot_home,slot_away,predicted_home_team,predicted_away_team,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,match_winner,penalties
0,73,Round of 32,1,2026-06-28T19:00:00Z,"SoFi Stadium, Los Angeles",Runner-up Group A,Runner-up Group B,None,None,None,None,None,None,None,None,None
1,74,Round of 32,1,2026-06-29T17:00:00Z,"NRG Stadium, Houston",Winner Group C,Runner-up Group F,None,None,None,None,None,None,None,None,None
2,75,Round of 32,1,2026-06-29T20:30:00Z,"Gillette Stadium, Boston",Winner Group E,Best 3rd (Groups A/B/C/D/F),None,None,None,None,None,None,None,None,None
3,76,Round of 32,1,2026-06-30T01:00:00Z,"Estadio BBVA, Monterrey",Winner Group F,Runner-up Group C,None,None,None,None,None,None,None,None,None
4,77,Round of 32,1,2026-06-30T17:00:00Z,"AT&T Stadium, Dallas",Runner-up Group E,Runner-up Group I,None,None,None,None,None,None,None,None,None
5,78,Round of 32,1,2026-06-30T21:00:00Z,"MetLife Stadium, East Rutherford",Winner Group I,Best 3rd (Groups C/D/F/G/H),None,None,None,None,None,None,None,None,None
6,79,Round of 32,1,2026-07-01T01:00:00Z,"Estadio Azteca, Mexico City",Winner Group A,Best 3rd (Groups C/E/F/H/I),None,None,None,None,None,None,None,None,None
7,80,Round of 32,1,2026-07-01T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Group L,Best 3rd (Groups E/H/I/J/K),None,None,None,None,None,None,None,None,None
8,81,Round of 32,1,2026-07-01T20:00:00Z,"Lumen Field, Seattle",Winner Group G,Best 3rd (Groups A/E/H/I/J),None,None,None,None,None,None,None,None,None
9,82,Round of 32,1,2026-07-02T00:00:00Z,"Levi's Stadium, Santa Clara",Winner Group D,Best 3rd (Groups B/E/F/I/J),None,None,None,None,None,None,None,None,None
10,83,Round of 32,1,2026-07-02T19:00:00Z,"BMO Field, Toronto",Runner-up Group K,Runner-up Group L,None,None,None,None,None,None,None,None,None
11,84,Round of 32,1,2026-07-02T23:00:00Z,"SoFi Stadium, Los Angeles",Winner Group H,Runner-up Group J,None,None,None,None,None,None,None,None,None
12,85,Round of 32,1,2026-07-03T03:00:00Z,"BC Place, Vancouver",Winner Group B,Best 3rd (Groups E/F/G/I/J),None,None,None,None,None,None,None,None,None
13,86,Round of 32,1,2026-07-03T18:00:00Z,"AT&T Stadium, Dallas",Runner-up Group D,Runner-up Group G,None,None,None,None,None,None,None,None,None
14,87,Round of 32,1,2026-07-03T22:00:00Z,"Hard Rock Stadium, Miami",Winner Group J,Runner-up Group H,None,None,None,None,None,None,None,None,None
15,88,Round of 32,1,2026-07-04T01:30:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Group K,Best 3rd (Groups D/E/I/J/L),None,None,None,None,None,None,None,None,None
16,89,Round of 16,2,2026-07-04T17:00:00Z,"NRG Stadium, Houston",Winner Match 73,Winner Match 75,None,None,None,None,None,None,None,None,None
17,90,Round of 16,2,2026-07-04T21:00:00Z,"Lincoln Financial Field, Philadelphia",Winner Match 74,Winner Match 77,None,None,None,None,None,None,None,None,None
18,91,Round of 16,2,2026-07-05T20:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 76,Winner Match 78,None,None,None,None,None,None,None,None,None
19,92,Round of 16,2,2026-07-06T00:00:00Z,"Estadio Azteca, Mexico City",Winner Match 79,Winner Match 80,None,None,None,None,None,None,None,None,None
20,93,Round of 16,2,2026-07-06T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 83,Winner Match 84,None,None,None,None,None,None,None,None,None
21,94,Round of 16,2,2026-07-07T00:00:00Z,"Lumen Field, Seattle",Winner Match 81,Winner Match 82,None,None,None,None,None,None,None,None,None
22,95,Round of 16,2,2026-07-07T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 86,Winner Match 88,None,None,None,None,None,None,None,None,None
23,96,Round of 16,2,2026-07-07T20:00:00Z,"BC Place, Vancouver",Winner Match 85,Winner Match 87,None,None,None,None,None,None,None,None,None
24,97,Quarter-final,4,2026-07-09T20:00:00Z,"Gillette Stadium, Boston",Winner Match 89,Winner Match 90,None,None,None,None,None,None,None,None,None
25,98,Quarter-final,4,2026-07-10T19:00:00Z,"SoFi Stadium, Los Angeles",Winner Match 93,Winner Match 94,None,None,None,None,None,None,None,None,None
26,99,Quarter-final,4,2026-07-11T21:00:00Z,"Hard Rock Stadium, Miami",Winner Match 91,Winner Match 92,None,None,None,None,None,None,None,None,None
27,100,Quarter-final,4,2026-07-12T01:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Match 95,Winner Match 96,None,None,None,None,None,None,None,None,None
28,101,Semi-final,8,2026-07-14T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 97,Winner Match 98,None,None,None,None,None,None,None,None,None
29,102,Semi-final,8,2026-07-15T19:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 99,Winner Match 100,None,None,None,None,None,None,None,None,None
30,103,Third-place playoff,8,2026-07-18T21:00:00Z,"Hard Rock Stadium, Miami",Loser Match 101,Loser Match 102,None,None,None,None,None,None,None,None,None
31,104,Final,16,2026-07-19T19:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 101,Winner Match 102,None,None,None,None,None,None,None,None,None

## **Data Exploration & Preprocessing**

1. elo.csv - World Football Elo Ratings
2. history_stat.csv - FIFA World Cup History Statistics
3. former_names.csv

In [159]:
# Load historical_stat.csv and display the first few rows
history_stat = pd.read_csv('data/history_stat.csv')
history_stat.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [160]:
# Check years
history_stat.dtypes

date           object
home_team      object
away_team      object
home_score    float64
away_score    float64
tournament     object
city           object
country        object
neutral          bool
dtype: object

In [161]:
history_stat["date"] = pd.to_datetime(
    history_stat["date"],
    format="mixed",
    errors="coerce",
    utc=True
)

In [162]:
print("Earliest (oldest):", history_stat["date"].min())
print("Latest (newest):  ", history_stat["date"].max())
print("Oldest year:", history_stat["date"].min().year)
print("Newest year:", history_stat["date"].max().year)
print("Invalid dates:", history_stat["date"].isna().sum())

Earliest (oldest): 1872-11-30 00:00:00+00:00
Latest (newest):   2026-06-27 00:00:00+00:00
Oldest year: 1872
Newest year: 2026
Invalid dates: 0

In [163]:
history_stat.columns.to_list()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tournament',
 'city',
 'country',
 'neutral']

In [164]:
history_stat.describe()

         home_score    away_score
count  49215.000000  49215.000000
mean       1.756091      1.182404
std        1.770617      1.401770
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [165]:
# Load former_names.csv and display the first few rows
former_names = pd.read_csv('data/former_names.csv')
former_names.head()

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [166]:
former_names.columns.to_list()

['current', 'former', 'start_date', 'end_date']

In [167]:
# Load elo.csv and display the first few rows
elo = pd.read_csv('data/elo.csv', on_bad_lines="skip")
elo.head()

        Team   Elo
0      Spain  2165
1  Argentina  2113
2     France  2081
3    England  2020
4     Brazil  1984

In [168]:
elo.columns.to_list()

['Team', 'Elo']

In [169]:
# Check if any rows have former names
history_stat["home_team"].isin(former_names["former"]).sum()

0

In [170]:
history_stat["away_team"].isin(former_names["former"]).sum()

0

In [171]:
# Check if the names in the history_stat matched the names in the elo
history_teams = set(history_stat["home_team"]).union(set(history_stat["away_team"]))

elo_teams = set(elo["Team"])

common_history_elo = history_teams & elo_teams

print("Total history teams:", len(history_teams))
print("Total elo teams:", len(elo_teams))
print("Common teams:", len(common_history_elo))

Total history teams: 333
Total elo teams: 244
Common teams: 226

In [172]:
# Drop rows that have team names in home_team or away_team are not in elo
valid_teams = set(elo["Team"])

history_stat_clean = history_stat[
    history_stat["home_team"].isin(valid_teams) &
    history_stat["away_team"].isin(valid_teams)
].copy()

In [173]:
print("Original rows:", len(history_stat))
print("Clean rows:", len(history_stat_clean))
print("Dropped rows:", len(history_stat) - len(history_stat_clean))

Original rows: 49287
Clean rows: 44402
Dropped rows: 4885

In [174]:
all_WC26_Teams = set(group_fixtures["home_team"]).union(set(group_fixtures["away_team"]))

common = common_history_elo & all_WC26_Teams

print("Total all_WC26_Teams:", len(all_WC26_Teams))
print("Total elo teams:", len(elo_teams))
print("Common teams:", len(common))

Total all_WC26_Teams: 48
Total elo teams: 244
Common teams: 41

In [175]:
missing_in_WC26 = all_WC26_Teams - elo_teams

list(missing_in_WC26)

['USA',
 'UEFA Playoff C',
 'UEFA Playoff B',
 'UEFA Playoff A',
 'UEFA Playoff D',
 'FIFA Playoff 1',
 'FIFA Playoff 2']

In [ ]:
from feature_engineering import resolve_team_original_to_updated

In [177]:
history_stat_clean["home_team"] = history_stat_clean["home_team"].replace({"United States": "USA"})
history_stat_clean["away_team"] = history_stat_clean["away_team"].replace({"United States": "USA"})
elo["Team"] = elo["Team"].replace({"United States": "USA"})

In [178]:
#double check
elo_teams = set(elo["Team"])

missing_in_WC26 = all_WC26_Teams - elo_teams

list(missing_in_WC26)

['UEFA Playoff C',
 'UEFA Playoff B',
 'UEFA Playoff A',
 'UEFA Playoff D',
 'FIFA Playoff 1',
 'FIFA Playoff 2']

In [179]:
gf = group_fixtures.copy()
gf["home_team"] = gf["home_team"].map(resolve_team_original_to_updated)
gf["away_team"] = gf["away_team"].map(resolve_team_original_to_updated)

In [180]:
all_WC26_Teams_updated = set(gf["home_team"]).union(set(gf["away_team"]))
missing_in_WC26 = all_WC26_Teams_updated - elo_teams
missing_in_WC26

set()

In [181]:
from feature_engineering import combine_teams_elo, add_match_features

In [182]:
# Combine csv files - elo.csv, history_stat.csv
history_with_elo = combine_teams_elo(history_stat_clean, elo)

In [183]:
(history_with_elo["tournament"] == "Friendly").sum()

# Drop rows where matches are friendly matches
history_with_elo = history_with_elo[history_with_elo["tournament"] != "Friendly"].copy()

In [184]:
history_with_elo.isna().sum()

date           0
home_team      0
away_team      0
home_score    69
away_score    69
tournament     0
city           0
country        0
neutral        0
home_elo       0
away_elo       0
elo_diff       0
dtype: int64

In [185]:
history_with_elo = history_with_elo.dropna(subset=["home_score", "away_score"])

In [186]:
main_cols = [
    "date", "home_team", "away_team", "home_score", "away_score", "tournament", "neutral",
    "home_elo", "away_elo", "elo_diff"
]
raw_cols = [ # This will be used to check history games before coming to the next match
    "date", "home_team", "away_team", "home_score", "away_score", "tournament"
]

mydf = history_with_elo[main_cols].copy()
rawdf = history_with_elo[raw_cols].copy()

# Do preprocessing for rawdf
rawdf["date"] = pd.to_datetime(rawdf["date"], utc=True)

rawdf = rawdf.sort_values("date")

In [187]:
from collections import defaultdict

team_hist = defaultdict(list)

for r in rawdf.itertuples(index=False):
    team_hist[r.home_team].append(r)
    team_hist[r.away_team].append(r)

In [188]:
# Check row having missing values
mydf[mydf.isna().any(axis=1)].shape[0]

0

In [189]:
mydf = mydf.dropna()

In [190]:
# Create home advantage
mydf["home_advantage"] = mydf["neutral"].apply(lambda x: 0 if x == 1 else 1)

In [191]:
# Split data into 3 parts (train, validate, test)
# Note: not split randomly, train 1872 - 2018; validate 2019 - 2024; test 2025 - 2026

train_end = pd.Timestamp("2018-12-31", tz="UTC")
val_start = pd.Timestamp("2019-01-01", tz="UTC")
val_end   = pd.Timestamp("2024-12-31", tz="UTC")
test_start = pd.Timestamp("2025-01-01", tz="UTC")

mydf_train = mydf[mydf["date"] <= train_end].copy()
mydf_val   = mydf[(mydf["date"] >= val_start) & (mydf["date"] <= val_end)].copy()
mydf_test  = mydf[mydf["date"] >= test_start].copy()

print("train:", mydf_train.shape, mydf_train["date"].min(), "→", mydf_train["date"].max())
print("val:  ", mydf_val.shape,   mydf_val["date"].min(),   "→", mydf_val["date"].max())
print("test: ", mydf_test.shape,  mydf_test["date"].min(),  "→", mydf_test["date"].max())

train: (22925, 11) 1884-01-26 00:00:00+00:00 → 2018-12-15 00:00:00+00:00
val:   (4128, 11) 2019-01-05 00:00:00+00:00 → 2024-12-31 00:00:00+00:00
test:  (809, 11) 2025-01-02 00:00:00+00:00 → 2026-03-31 00:00:00+00:00

In [192]:
mydf_train = add_match_features(mydf_train, team_hist).copy()

In [194]:
mydf_val = add_match_features(mydf_val, team_hist).copy()
mydf_test = add_match_features(mydf_test, team_hist).copy()

#### check correlation between columns (PENDING)

In [196]:
# Save df as csv
mydf_train.to_csv("data/train.csv", index = False)
mydf_val.to_csv("data/val.csv", index = False)
mydf_test.to_csv("data/test.csv", index = False)
rawdf.to_csv("data/raw_history.csv")